name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'firefox'
        type: choice
        options:
          - chrome
          - firefox
          - safari

      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'dev'
        type: choice
        options:
          - qa
          - prod

permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run Tests
        run: mvn test -PRegression -Dbrowser=${{ github.event.inputs.browser }} -Denv=${{ github.event.inputs.environment }}
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.15
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always() && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report