name: Regression Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: Select Browser
        required: true
        type: choice
        options:
          - chrome
          - firefox
        default: chrome

      environment:
        description: Select Environment
        required: true
        type: choice
        options:
          - qa
          - dev
          - prod
        default: qa

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run Regression Tests
        run: |
          echo "Browser: ${{ inputs.browser }}"
          echo "Environment: ${{ inputs.environment }}"
          mvn test -PRegression -Dbrowser=${{ inputs.browser }} -Denv=${{ inputs.environment }}